/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Generated By:JavaCC: Do not edit this line. ISEParserConstants.java */
package org.apache.metron.parsers.ise;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface ISEParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int C_SINGLE_COMMENT = 1;
  /** RegularExpression Id. */
  int C_MULTILINE_COMMENT = 2;
  /** RegularExpression Id. */
  int SH_SINGLE_COMMENT = 3;
  /** RegularExpression Id. */
  int EOL = 4;
  /** RegularExpression Id. */
  int COMMA = 5;
  /** RegularExpression Id. */
  int EQUALS = 6;
  /** RegularExpression Id. */
  int SLASH = 7;
  /** RegularExpression Id. */
  int TAG = 8;
  /** RegularExpression Id. */
  int STRING_BODY = 9;
  /** RegularExpression Id. */
  int BRACED_STRING = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<C_SINGLE_COMMENT>",
    "<C_MULTILINE_COMMENT>",
    "<SH_SINGLE_COMMENT>",
    "<EOL>",
    "\",\"",
    "\"=\"",
    "\"\\\\\"",
    "\"(tag=0)\"",
    "<STRING_BODY>",
    "<BRACED_STRING>",
  };

}
