#!/usr/bin/env bash
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# metron rest application service
# chkconfig: - 20 80
# description: rest application
# processname: metron-rest
#
if [ -f /etc/rc.d/init.d/functions ]; then
    . /etc/rc.d/init.d/functions
fi

NAME=metron-rest
DESC="Metron REST Application"
METRON_VERSION=${project.version}
METRON_HOME=/usr/metron/$METRON_VERSION
METRON_LOG_DIR="/var/log/metron"
METRON_PID_DIR="/var/run/metron"
METRON_USER="metron"
METRON_GROUP="metron"
METRON_REST_PORT=8082
METRON_JDBC_PASSWORD="$2"
METRON_SYSCONFIG="/etc/sysconfig/metron"
if [ -f "$METRON_SYSCONFIG" ]; then
    set -a
    . "$METRON_SYSCONFIG"
fi

PIDFILE="$METRON_PID_DIR/$NAME.pid"
LOCKFILE=/var/lock/subsys/$NAME

# the vagrant Spring profile provides configuration values, otherwise configuration is provided by rest_application.yml
if [[ !($METRON_SPRING_PROFILES_ACTIVE == *"vagrant"*) ]]; then
  METRON_SPRING_OPTIONS+=" --spring.config.location=$METRON_HOME/config/rest_application.yml"
fi
METRON_SPRING_OPTIONS+=" --server.port=$METRON_REST_PORT"
if [ $METRON_SPRING_PROFILES_ACTIVE ]; then
    METRON_SPRING_OPTIONS+=" --spring.profiles.active=$METRON_SPRING_PROFILES_ACTIVE"
fi
if [ $METRON_JDBC_PASSWORD ]; then
    METRON_SPRING_OPTIONS+=" --spring.datasource.password=$METRON_JDBC_PASSWORD"
fi
if [ $METRON_JDBC_CLIENT_PATH ]; then
    METRON_JVMFLAGS+=" -Dloader.path=$METRON_JDBC_CLIENT_PATH"
fi
DAEMON="java $METRON_JVMFLAGS -jar $METRON_HOME/lib/metron-rest-$METRON_VERSION.jar $METRON_SPRING_OPTIONS"

#
# start the rest application
#
start() {  

  # if pidfile exists, do not start another
  if [ -f $PIDFILE ]; then
      PID=`cat $PIDFILE`
      printf "OK [$PID]\n"
      return
  fi

  if [ ! -d "$METRON_LOG_DIR" ]; then
      mkdir -p "$METRON_LOG_DIR" && chown "$METRON_USER":"$METRON_GROUP" "$METRON_LOG_DIR"
  fi

  if [ ! -d "$METRON_PID_DIR" ]; then
      mkdir -p "$METRON_PID_DIR" && chown "$METRON_USER":"$METRON_GROUP" "$METRON_PID_DIR"
  fi

  # kick-off the daemon
  PID=`runuser -s /bin/bash $METRON_USER -c "$DAEMON" >> $METRON_LOG_DIR/$NAME.log 2>&1 & echo $!`

  if [ -z $PID ]; then
      printf "Fail\n"
  else
      echo $PID > $PIDFILE && touch $LOCKFILE
      printf "Ok [$PID]\n"
  fi
}

#
# stop the rest application
#
stop() {
  if [ -f $PIDFILE ]; then
      PID=`cat $PIDFILE`
      killproc -p $PIDFILE metron-rest
      RETVAL=$?
      echo
      [ $RETVAL -eq 0 ] && rm -f $LOCKFILE
      printf "Stopped [$PID]\n"
  else
      printf "Not running\n"
  fi
}

#
# status check of the rest application
#
rest_status() {
  status -p $PIDFILE metron-rest
}

case "$1" in

  ##############################################################################
  # start
  #
  start)
    printf "%-50s \n" "Starting $NAME..."
    start
  ;;

  ##############################################################################
  # status
  #
  status)
    printf "%-50s \n" "Checking $NAME..."
    rest_status
  ;;

  ##############################################################################
  # stop
  #
  stop)
    printf "%-50s \n" "Stopping $NAME..."
    stop
  ;;

  ##############################################################################
  # restart
  #
  restart)
    $0 stop
    $0 start $2
  ;;

  ##############################################################################
  # reload
  #
  reload)
  ;;

  *)
    echo "Usage: $0 {status|start|stop|restart}"
    exit 1
esac
