# -*- mode: ruby -*-
# vi: set ft=ruby :

hosts = [
  { hostname: "node1", ip: "192.168.66.101", memory: "2048", cpus: 2 },
  { hostname: "node2", ip: "192.168.66.102", memory: "2048", cpus: 2 },
  { hostname: "node3", ip: "192.168.66.103", memory: "2048", cpus: 2 },
  { hostname: "node4", ip: "192.168.66.104", memory: "2048", cpus: 2 }
]

Vagrant.configure(2) do |config|

  # all hosts built on centos 6
  config.vm.box = "bento/centos-6.7"
  config.ssh.insert_key = "true"

  # enable the hostmanager plugin
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

  # define each host
  hosts.each_with_index do |host, index|
    config.vm.define host[:hostname] do |node|

      # host settings
      node.vm.hostname = host[:hostname]
      node.vm.network "private_network", ip: host[:ip]

      # vm settings
      node.vm.provider "virtualbox" do |vb|
        vb.memory = host[:memory]
        vb.cpus = host[:cpus]

        # enable promisc mode on the network interface
        if host.has_key?(:promisc)
          vb.customize ["modifyvm", :id, "--nicpromisc#{host[:promisc]}", "allow-all"]
        end
      end

      # provisioning; only after all hosts created
      if index == hosts.size - 1
        node.vm.provision :ansible do |ansible|
          ansible.playbook = "../../playbooks/metron_full_install.yml"
          ansible.sudo = true
          ansible.inventory_path = "../../inventory/singlenode-vagrant"
        end
      end
    end
  end
end
