#!/usr/bin/env node

// Script to generate sample alerts

var kafka = require('../lib/modules/kafka')
  , Chance = require('chance')
  , chance = new Chance()

  // Number of randomly-generated messages per second
  , mps = 5
  , topic = 'opensoc'
  , dashboardCount = 10;

var dashboards = [];

for (var i = 0; i < dashboardCount; i++) {
  dashboards.push({
    title: chance.sentence({
      words: chance.integer({ min: 1, max: 7 })
    }).replace(/\./, '')
  });
}


// Fire off random text
setInterval(function () {
  var message = dashboards[chance.integer({ min: 0, max: dashboardCount-1 })];

  kafka.produce(topic, JSON.stringify(message), function (err, result) {
    console.log('Sending Text:');
    console.log(message);
    console.log();
    console.log('Reply from kafka server:');
    console.log(result);
    console.log();
    console.log();
  });
}, 1000 / mps);
