#!/usr/bin/env node

var spawn = require('child_process').spawn
  , sax = require('sax')
  , saxpath = require('saxpath')
  , xml2js = require('xml2js')
  , url = process.argv[2];

if (process.argv.length !== 3) {
  console.log('Usage: script/parse [URL of pcap]');
  process.exit(1);
}

// reset all sax entities
for (var entity in sax.ENTITIES) {
  sax.ENTITIES[entity] = '&' + entity + ';';
}

var PCAPToJSON = function (pcapUrl, cb) {
  var saxParser = sax.createStream(true)
    , streamer = new saxpath.SaXPath(saxParser, '/pdml/packet')
    , parser = new xml2js.Parser()
    , curl = spawn('curl', ['-s', pcapUrl])
    , tshark = spawn('tshark', ['-i', '-', '-T', 'pdml']);

  streamer.on('match', function (xml) {
    parser.parseString(xml, function (err, result) {
      if (err) {
        console.log('problem with xml chunk:');
        console.log(xml);
        throw err;
      } else {
        cb(result);
      }
    });
  });

  curl.stdout.pipe(tshark.stdin);
  tshark.stdout.pipe(saxParser);
};

PCAPToJSON(url, function (json) {
  // uncomment to output formatted JSON
  console.log(JSON.stringify(json, null, 2));

  // uncomment to output condensed JSON
  // console.log(JSON.stringify(json));
});
